### ISSUE TITLE
Compat.round can't be used with only one keyword argument

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/Compat.jl#581] opened 2018-06-19 22:49 UTC
On 0.6:
```
julia> using Compat

julia> Compat.round(0.005, digits=3)
ERROR: UndefVarError: base not defined
Stacktrace:
 [1] (::Compat.#kw##round)(::Array{Any,1}, ::Compat.#round, ::Float64) at ./<missing>:0
```
On 0.7, `round(0.005, digits=3)` works as expected.

**Comment by martinholters** [comment] 2018-06-20 06:16
Duplicate of #567.

**Closed by martinholters** 2018-06-20 06:16 UTC

**Comment by ararslan** [comment] 2018-06-20 17:54
Ah, thanks.
